### ISSUE TITLE
添加pr规则检查

### ISSUE THREAD

**Issue by k90zz** [atomeocean/atomeocean-cn-mapstruct#38]
## User story

利用github actions检查提交的pr能否通过build，如果失败会提前禁止合并到main分支

## Prerequisites (if any)

actions草稿如下

```yaml
name: PR Build Validation

on:
  pull_request:
    branches: [ main ]  # 监控目标分支（根据实际情况修改）
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # 指定你的 Node 版本

      - name: Install dependencies
        run: npm ci          # 比 npm install 更严格，适合 CI

      - name: Run build
        run: npm run build   # 关键构建步骤
```

## Acceptance Criteria

- [ ] 

## Follow-up work (if applicable)
